# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club', models.CharField(max_length=30)),
                ('Club_PL', models.CharField(max_length=30)),
                ('FullName', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=30)),
                ('Founded', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClubRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round', models.CharField(max_length=10)),
                ('Rank', models.IntegerField(null=True)),
                ('Points', models.IntegerField(null=True)),
                ('GoalsFor', models.IntegerField(null=True)),
                ('GoalsVs', models.IntegerField(null=True)),
                ('ClubFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Event', models.CharField(max_length=30)),
                ('Score', models.IntegerField(null=True)),
                ('GK', models.IntegerField(null=True)),
                ('DF', models.IntegerField(null=True)),
                ('MF', models.IntegerField(null=True)),
                ('FW', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round', models.CharField(max_length=10)),
                ('PlayDate', models.DateTimeField()),
                ('GoalsHome', models.IntegerField(null=True)),
                ('GoalsAway', models.IntegerField(null=True)),
                ('ScorersHome', models.CharField(max_length=200, null=True)),
                ('ScorersAway', models.CharField(max_length=200, null=True)),
                ('ClubAwayFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_away', to='football.Club')),
                ('ClubHomeFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_home', to='football.Club')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTime', models.TimeField()),
                ('Position', models.CharField(max_length=10, null=True)),
                ('EventClubFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.Club')),
                ('EventFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Event')),
                ('GameFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('DateOfBirth', models.DateField()),
                ('ProfilePhoto', models.CharField(default='_profile.jpg', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionDef', models.CharField(max_length=10)),
                ('ShirtNo', models.CharField(max_length=10)),
                ('ClubFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Club')),
                ('PlayerFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=30)),
                ('League', models.CharField(max_length=30)),
                ('TimeFrame', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='playerinclub',
            name='SeasonFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='PlayerFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='SeasonFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
        ),
        migrations.AddField(
            model_name='clubranking',
            name='SeasonFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('SeasonFK', 'Round', 'ClubHomeFK')]),
        ),
    ]
