# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='Club_PL',
        ),
    ]
