# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('JoinDate', models.DateTimeField()),
                ('UserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('CreateDate', models.DateTimeField()),
                ('ChatText', models.CharField(max_length=100, null=True)),
                ('UserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashID', models.CharField(max_length=16)),
                ('IP', models.CharField(max_length=16, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('Region', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('TimeZone', models.CharField(max_length=60, null=True)),
                ('FavClubSet', models.BooleanField(default=False)),
                ('Slogan', models.CharField(max_length=100, null=True)),
                ('Icon', models.CharField(max_length=100, null=True)),
                ('Pref_FriendsRealName', models.BooleanField(default=True)),
                ('Pref_FriendsEmail', models.BooleanField(default=True)),
                ('BotAI', models.IntegerField(default=0)),
                ('Diamonds', models.IntegerField(default=10)),
                ('LifetimeDiamonds', models.IntegerField(default=10)),
                ('FavClubFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.Club')),
                ('UserFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationValue', models.IntegerField(null=True)),
                ('User1FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('User2FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
